CONTENT_TYPE = "Content-Type"
CONTENT = "Content-"
APPLICATION_JSON = "application/json"

UTF8 = "utf8"

AUTHORIZATION = "Authorization"
BASIC = "Basic cGVyZm9ybTU6VWxpbmUxMjM="
BEARER = "Bearer"
TOKEN = "token"

COMPANY_CODE = "companyCode"
US_COMP_CODE = "UL-US"
CATALOG_CODE = "catalogCode"
FV_CC = "FV"
SOURCE_APPLICATION = "sourceApplication"
JOE_PHONE = "JOE-PHONE"
ORDER_TYPE = "orderType"
WRITTEN_ORDER = "WRITTEN_ORDER"
PRIORITY_SOURCE_CODE = "prioritySourceCode"
CUSTOMER_PURCHASE_ORDER_NUMBER = "customerPurchaseOrderNumber"
G2HOLD = "G2HOLD"
FINDER_SOURCE_CODE = "finderSourceCode"
KEEP_LOCKED = "keepLocked"
MEXICO_USAGE_CODE = "mexicoUsageCode"
POI = "P01"
BILL_TO_CUSTOMER_ID = "billToCustomerId"
SHIP_TO_CUSTOMER_ID = "shipToCustomerId"
CONTACT_ID = "contactId"
ORDER_NUMBER = "orderNumber"
AUTO_ASSIGN_NUM = "autoAssignOrderNumber"

FIVE_BILLION = 5000000000

ADDRESS_LINE = "addressLine"
ADDRESS_LINE1 = "addressLine1"
CITY = "city"
CUSTOMER_NAME = "customerName"
CUSTOMER_NUMBER = "customerNumber"
POSTAL_CODE = "postalCode"
STATE_PROV_CODE = "stateProvinceCode"
STATE = "state"
ZIP = "zipCode"

NAME = "name"
EMAIL = "emailAddress"

LINES = "lines"
ITEM_ID = "itemId"
PRODUCT_ID = "productId"
SELLABLE_ORDERED_QTY = "sellableOrderedQuantity"
EXT_PRICE = "extendedPrice"
RA_CODE = "raCode"

MODEL_NUM = "modelNumber"
QTY = "quantity"

CONTACT_NAME = "contactName"
CONTACT_EMAIL = "contactEmailAddress"
CONTACT_MOBILE = "contactMobileNumber"

SHIP_TO_NAME = "shipToCustomerName"
SHIP_TO_ADD1 = "shipToAddress1"
SHIP_TO_ADD2 = "shipToAddress2"
SHIP_TO_CITY = "shipToCity"
SHIP_TO_STATE = "shipToStateProvinceCode"
SHIP_TO_POSTAL = "shipToPostalCode"
SHIP_TO_EXT = "shipToPostalCodeExtension"
SHIP_TO_COUNTRY = "shipToCountryCode"

PAYMENT_TYPE = "paymentTypeCode"
NET_30 = "NET_30"
TAX_OVERRIDE = "taxOverridden"
SOURCE_CODE = "selectedSourceCode"
SELECTED_SOURCE = "selectedSource"
FTWEB = "FTWEB"
SUBMISSION_MODE = "submissionMode"
PARALLEL = "PARALLEL"

GENERAL_INFO = "generalInfo"
CHECKOUT_REQ_ID = "checkoutRequestId"

LINE = "line"

CUST_MARKED_DEL = "customerMarkedForDeletion"
MARKED_DEL = "markedForDeletion"

EMPTY = ""